spring:
  datasource:
    url: jdbc:sqlserver://gosmart.database.windows.net:1433;database=gosmart-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: isal-man
    password: kataKata123
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 7060